default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:206487358108:android:87beb12dbee72013793b59",
        firebase_cli_token: "1//03TRWNYJa3mzTCgYIARAAGAMSNwF-L9IraoG0sgyxgrdgu426MKyGS1Wqj48lp5KqQt7lmcbaLvT5XoRsFk2RKPj_4-4tldDYKaQ",
        # android_artifact_type : "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "eslamkhalil920@gmail.com",
        release_notes: "testing automation in!"
    )
  end
end